version: "3.8"

services:

  panel:
    image: ghcr.io/mcplaynetwork/panel:develop
    container_name: panel
    restart: always
    ports:
      - 49610:80
    volumes:
      - panel-data:/app/var/
      - panel-logs:/app/storage/logs
    environment:
      APP_URL: ${APP_URL}
      APP_TIMEZONE: ${APP_TIMEZONE}
      APP_SERVICE_AUTHOR: ${APP_SERVICE_AUTHOR}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_ENVIRONMENT_ONLY: ${APP_ENVIRONMENT_ONLY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      HASHIDS_SALT: ${HASHIDS_SALT}
      HASHIDS_LENGTH: ${HASHIDS_LENGTH}
      CACHE_DRIVER: ${CACHE_DRIVER}
      SESSION_DRIVER: ${SESSION_DRIVER}
      QUEUE_DRIVER: ${QUEUE_DRIVER}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      MAIL_DRIVER: ${MAIL_DRIVER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_FROM: ${MAIL_FROM}
#      MAIL_USERNAME: ${MAIL_USERNAME}
#      MAIL_PASSWORD: ${MAIL_PASSWORD}

volumes:
  panel-data:
    external: true
  panel-logs:
    external: true

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
